# Generated by Django 5.2.7 on 2025-12-13 16:35

import Document.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=Document.models.document_upload_path),
        ),
    ]
