# Generated by Django 5.2.7 on 2025-12-18 19:14

import Audio.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Document', '0002_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to=Audio.models.audio_upload_path)),
                ('file_size', models.BigIntegerField(help_text='Audio file size bytes')),
                ('duration', models.IntegerField(blank=True, help_text='Audio duration in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='Document.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
